services:
  db:
    image: postgres:16
    container_name: twitchplanner_db
    environment:
      POSTGRES_USER: twitchplanner
      POSTGRES_PASSWORD: twitchplanner
      POSTGRES_DB: twitchplanner
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
